name: "olio"
description: horoli's oilo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  http: ^0.13.4
  flutter:
    sdk: flutter
    
  tnd_core:
    git:
      url: 'https://git.technolda.com/Technolda/tnd_core.git'
      ref: v2

  tnd_pkg_widget:
    git:
      url: 'https://git.technolda.com/Technolda/tnd_pkg_widget.git'
      ref: v2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
